### ISSUE TITLE
platform

### ISSUE THREAD

**Issue by ddaaggeett** [ddaaggeett/climblogger#1]
so first things first.

are you thinking desktop or mobile, or both? we'll start development on the mobile side - i know the main user base will be mobile

**Comment by ddaaggeett** [comment]
@tinysiren - the main project [page](https://github.com/tinysiren/Climbing-log) should be clear cut to get up and running

**Comment by tinysiren** [comment]
Yes, mobile sounds like the better starting point.  Preferably, an app would be used to take care of reading the tag on a route.  A climber would start up the app when getting ready to climb.  Then once they ascend the route, and the climber is supported (rope is taught), they are free to get their phone out of their pocket and scan/read the tag.  Hmm, I suppose the tags could be bar codes too and read by the camera.  That might be easier to implement.

**Comment by ddaaggeett** [comment]
sure. i've never done it before but we can use a [QR scan](https://www.google.com/search?q=qur+scan&source=lnms&tbm=isch&sa=X&ved=0ahUKEwik0bbbkMbZAhUkuVkKHYqXDoMQ_AUICygC&biw=1887&bih=990)

**Comment by ddaaggeett** [comment]
so the git download came with a user interface program?

**Comment by ddaaggeett** [comment]
@tinysiren - so i figured out the issue i'm facing. i've been trying to connect to the mobile application to the database but the connection server is using the server that exists for a different piece of software on my computer. not sure why a new application with its own database instance is writing to an entirely different database instance. hopefully this hiccup won't be long

**Comment by ddaaggeett** [comment]
we're up and running with the mobile platform connected with a realtime database
